### PR TITLE
Make shared/static library generation cmake configurable

### PR DESCRIPTION
**Pull request by nmcglohon**
Commit 671a00d0e1137814f8071bbc243c4355af316f3d changed the build behavior of ROSS to install both shared and static libraries `libROSS.a` and `libROSS.so`. This can interfere with the standard vanilla installation of CODES and could interfere with other projects that utilize ROSS libraries in an ambiguous manner (i.e. looking for libROSS generally without paying specific attention to the extension or library type).

This pull request includes a single commit that reverts _default_ behavior of ROSS regarding library generation to that of the state before commit 671a00d0e1137814f8071bbc243c4355af316f3d. 

That being said, it is understandable that users may want the ability to utilize either static or shared libraries (or both). To accommodate this, I've made the generation of static and shared libraries to be CMAKE configurable `ON` or `OFF`.

The pertinent options are:
- `ROSS_enable_shared` (default OFF)
- `ROSS_enable_static` (default ON)

If the user attempts to disable both of these options, CMAKE will throw an error notifying the user that at least one of them must be turned on. While not every user of ROSS necessarily utilizes the installed libROSS.*, this ensures that at the very least the standard behavior of ROSS as described in any documentation remains accurate going forward. This helps prevent the situation where a user disables both of them inadvertently and then wonders why their project is failing to load libROSS.

---

If this merge represents a feature addition to ROSS, the following items must be completed before the branch will be merged:

- [ ] Document the feature on the blog (See the [website Contributing guide](https://github.com/ROSS-org/ross-org.github.io/blob/master/CONTRIBUTING.md)).
  Include a link to your blog post in the Pull Request.
- [ ] Builds should cleanly compile with -Wall and -Wextra.
- [ ] One or more TravisCI tests should be created (and they should pass)
- [ ] Through the TravisCI tests, coverage should increase
- [ ] Test with CODES to ensure everything continues to work

### CODE REVIEW

**Comment by gonsie** [comment]
What goes wrong with the CODES installation? Could we update our pkg-config file instead?

The reason to generate both is because the linker often enforces one or the other. For example, Cray machines will often force static linking (there may still be some bugs in the Cmake in this case). By building both, the linker can find the one it wants without a user having to rerun the configure/build.

**Comment by caitlinross** [comment]
So part of this is my fault.  I told Neil that we're switching up the branching workflow. And it's been started, but I haven't finished the blog post yet. So @gonsie made the fix related to this in #135, that's now been merged into develop, but not master yet. I guess there will be some initial growing pains. 

I do partially agree with Neil.  However, I think the default should be to generate both shared and static libraries, but give the user the option to disable on or the other if they want. That's pretty common among other libraries, right? So it seems like a reasonable option to add.

**Comment by nmcglohon** [comment]
Yeah I hadn't realized there was a develop branch yet. CODES, at least from the current master commit fails to build out of the box with the standard instructions. As it for some reason isn't able to handle the shared library. Sounds like maybe that was fixed in #135?

So long as general default behavior still works with CODES, I don't _need_ to have the option to disable one or the other. Just figured it'd be nice.

Also - I know my PR failed anyway and why as well. I'll fix it in case y'all want it anyway.

**Comment by caitlinross** [comment]
Just did some looking around, it looks like the better way is to actually not specifically set static and shared libraries.  The `add_library` command shouldn't specify static or shared, Cmake will build the right library based on the value of `BUILD_SHARED_LIBS`.  So closing this PR.

**Pull request closed without merging**
