### PR TITLE
ROSS cleanup

### PR DESCRIPTION
**Pull request by caitlinross**
Working on removing some unnecessary code from ROSS (e.g., some old pthreads stuff).  Also planning to add in some more documentation, to make things a little easier for future ROSS devs. 

Removed tw_memory functionality for now, since its status is unknown.  It maybe be reintroduced in the future.

Still doing some work on this branch, but wanted to get Travis tests running on what I've done so far. 

---

If this merge represents a feature addition to ROSS, the following items must be completed before the branch will be merged:

- [ ] Document the feature on the blog (See the [Contributing guide](https://github.com/carothersc/ROSS/blob/gh-pages/CONTRIBUTING.md) in the gh-pages branch).
  Include a link to your blog post in the Pull Request.
- [ ] Builds should cleanly compile with -Wall and -Wextra. 
- [ ] One or more TravisCI tests should be created (and they should pass)
- [ ] Through the TravisCI tests, coverage should increase
- [x] Test with CODES to ensure everything continues to work

### CODE REVIEW

**Comment by gonsie** [comment]
@caitlinross I have marked the [ROSS-Models](https://github.com/ROSS-org/ROSS-Models) as read-only. I think that is best, since the models won't get update with ROSS api changes.

Other than some testing, is there anything else needed for this branch? I don't think a blog post is necessary.

**Comment by caitlinross** [comment]
I don't think anything else is needed. I think I did already test with CODES, but I'll rerun tests today just to make sure.

**Comment by caitlinross** [comment]
I forgot I did have to make a small change to CODES. This branch changes `g_tw_pe` from an array of pointers to PEs to just a single PE pointer, since we're not using threads for PEs anymore.  Besides that, things seem good with CODES. I'm not sure though when the necessary change for CODES will be merged though. Misbah is out of town for a bit and I don't know who else has the ability to merge pull requests for CODES (I don't though).  

On another note, adding the creation of the shared library to ROSS seems to mess up the CODES build (it says it can't find libROSS.so when trying to run a simulation). Which is probably something that should be addressed in CODES, but should we add an option to the ROSS build process to disable shared libraries?  I remember on the BGQ you couldn't do shared libraries, not sure if the Power9 systems are the same,  but if so, we should probably add in that option, right @gonsie?

**Comment by gonsie** [comment]
Not being able to find the library sounds like a very common problem with incorrect rpath/linking settings in CMake. I’ll check it out with a full build and install with CODES. 

BGQ and Cray systems both have issues with shared libraries. I think both platforms let you make a shared lib... they just end up using static linking under the covers.

**Comment by gonsie** [comment]
@caitlinross yep, it was definitely an rpath issue. The fix was adding rpath link options to the `ross.pc` file. 

What I suspect was happening is that pkg-config was choosing the dynamic library by default (although it really shouldn't be doing that because the CODES configure was asking for `pkg-config --static`). Now it might still be selecting the dynamic ROSS, but the rpaths are set up properly 😕

**Comment by caitlinross** [comment]
Perfect! Thanks! So I think this is pretty much ready to merge, except figuring out who on the CODES side will merge my PR there.  We should do them together, since there is technically a slight API change that will break CODES.

**Comment by gonsie** [comment]
The codes changes are at [GL:codes/codes!82](https://xgitlab.cels.anl.gov/codes/codes/merge_requests/82). Since this changes an API we should roll out a new version (for spack reasons).

**Pull request merged**
